### ISSUE TITLE
Change files extentions from ".pde" to ".java" for the classes that don't use the processing functions

### ISSUE THREAD

**Issue by John-WL** [John-WL/EffectiveCollisionsGame#2]
Maybe we should only use processing as a gui canvas printer instead? Or should we use processing as the main engine to run all of our code? 

I think we need to discuss more in depth our engine hierarchy.

**Comment by lebel-louisjacob** [comment]
clearly, we could find ourselves wanting to change the gui technology. We discussed it a bit already, but do you have an idea of how to include Processing-generated `.java` class into a source code `.java` class?

**Comment by John-WL** [comment]
I thought we could let the gui classes in the .pde fileformat. What do you think?

**Comment by lebel-louisjacob** [comment]
We just talk IRL, and concluded that the backend should be a dependency of the frontend, and not the other way around. So we'll simply import a Java-only backend in a Processing frontend. We might end up packaging the backend in a separate library (which would only expose publicly a simple API) if it becomes huge enough, but for now I think this is going to be unnecessary.

**Comment by John-WL** [comment]
alright that looks fine for now

**Comment by John-WL** [comment]
same heeeerere
